ALTER TABLE anggota
ADD COLUMN IF NOT EXISTS foto_locked BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE galeri
ADD COLUMN IF NOT EXISTS is_locked BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE site_settings
ADD COLUMN IF NOT EXISTS instagram_image_locked BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS tiktok_image_locked BOOLEAN NOT NULL DEFAULT FALSE;
